name: deploy-gaissa
services:
  deploy-api:
    public: true
    image: fjdurlop/deploy-GAISSA:latest
    build: .
    replicas: 1
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
