name: deploy-gaissa
services:
  deploy-api:
    public: true
    image: GAISSA-UPC/cloud-api:latest
    build: .
    replicas: 1
    ports:
      - 8080
    resources:
      cpu: 2000m
      memory: 5Gi
